title: "Priya | Product Designer"
description: "Digital Product Designer based in Bangalore, India."
url: ""
baseurl: ""

# GitHub Pages configuration
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Exclude from processing
exclude:
  - README.md
  - .gitignore
  - .nojekyll